FROM balenalib/%%RESIN_MACHINE_NAME%%-debian

MAINTAINER Shaun Mulligan <shaun@balena.io>

RUN apt-get update && apt-get install -yq \
    python && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY src/mmcli /usr/bin/mmcli
COPY src/mmcli_libs /usr/lib
COPY src/start.sh start.sh
COPY src/speedtest.py speedtest.py
RUN chmod +x /usr/bin/mmcli

CMD ["bash", "/usr/src/app/start.sh"]