FROM balenalib/%%RESIN_MACHINE_NAME%%-debian

MAINTAINER Shaun Mulligan <shaun@balena.io>

RUN install_packages python modemmanager

WORKDIR /usr/src/app

COPY src/start.sh start.sh
COPY src/speedtest.py speedtest.py

CMD ["bash", "/usr/src/app/start.sh"]